import type { Meeting } from "./types";

const QA_RAW = `# Sponic Gardens - Sonia q&A Rahul.m4a

**Rahul Sonnad** *[00:00]*: The airlines have their airline points and flights. You kind of get better values and then they radically change those. So they work completely differently now as how they work 10 years ago and such. So I, I think we'll figure something out there. And I think you want to reward targeted earlier people with incentives that may last in perpetuity, which is what happens when you get like, that's what you do with employees. You give them stock options.
**Rahul Sonnad** *[00:34]*: Yeah.
**Rahul Sonnad** *[00:35]*: Which effectively last, you know, as long as the company is growing, they have these options and they keep becoming more and more valuable to the point where if you're working at Nvidia and you started 20 years ago as a secretary or like, you know, worth $100 million, like so. Yeah, but, but I don't feel like it's kind of a. I mean, I think you always do that with employees to provide incentive in any tech startup scenario. And I think you'll want to do it with, you know, select contributors. Like, like they'll be not employees, but there'll be people who are contributing. Facilitators, growers, prize.
**Rahul Sonnad** *[01:21]*: Yeah.
**Rahul Sonnad** *[01:22]*: Flower people or whatever. And you give them some. Yeah.
**Rahul Sonnad** *[01:26]*: So you see some rewards and such contribution.
**Sonia Wendorff** *[01:29]*: Yeah, but I'd say that's kind of not like a core. Like you could not do any of that and I don't think it hurts. But like, I think the business model is viable without any of that. I think doing that makes it, you know, slightly better.
**Rahul Sonnad** *[01:46]*: Yeah, Well, I think that ties into another topic, which is how much autonomy would you want to have around the things that are happening and. Or like. Yeah. In, in Spawnic Gardens.
**Rahul Sonnad** *[02:01]*: I feel like when you say autonomy.
**Rahul Sonnad** *[02:04]*: Like decision making power, or just like us facilitating everything versus people coming in and hosting events and just creating that layer of contributors, facilitators that are bringing people in, I think it's crucial to make it work.
**Rahul Sonnad** *[02:24]*: Yeah, I think that's like one of the more important questions. And my general, like, I mean, I think you got to kind of try things and see how they go. But like, I think generally you need a very kind of strict framework and guidelines. But within that you let people do what they want. But if they're like, there will always be a survey at the end where people are.
**Rahul Sonnad** *[02:49]*: Yeah.
**Sonia Wendorff** *[02:50]*: Rating it. There will, you know, there will always be, I don't know, certain marketing materials that will be created.
**Rahul Sonnad** *[02:57]*: Right. And data harvesting within that business or whatever.
**Rahul Sonnad** *[03:02]*: You know, we'll always, yeah. Do the data harvesting, but like the actual, like I want to run an educational thing like what that is. Anybody could decide and flash mob it, you know, so whoever's there who's interested in X could go see that. And I think like in that case the company doesn't need to be prescriptive at all. The topic, the topic could be alien sightings or you know, orange pesticides, whatever. But like how that operates and figuring out whether that gets to go again, figuring out whether the person who, you know, facilitated that is any good and should be given more resources and promotion or less.
**Rahul Sonnad** *[03:52]*: Right. Because in the pitch you mentioned toma, you know, in the very beginning, that would be one event a week and. Yeah, and I feel like investing into creating the network of people that already have their network is probably the best thing we can do to actually bring people to the location because they're just gonna, you know, there's lots of creators and interesting people that don't really have a venue to post things in or don't have the resources and very much benefit from having that type of structure. Plus being more tech forward than they probably are. So I feel like we should probably go for more like crowdsource programming from the very beginning.
**Sonia Wendorff** *[04:38]*: I think that's right. But I think the crowdsource programming has to be like cohesive. Like you can't have yoga, yoga. So you have to have like yoga, food, drink, music, you know, something that makes sense, you know, in terms of its overall structure. Okay, so.
**Rahul Sonnad** *[05:06]*: And then what kind of.
**Rahul Sonnad** *[05:08]*: Yeah, but I wouldn't envision like us facilitating no anything. We can maybe MC a little bit in the beginning, but it just won't be workable. So yeah, we're going to have to find the facilitators. But I, I think there's two directions you could go there. One is you can kind of say you've got your X thing, just bring your X thing here. Or we can say, hey, we've got this framework, what would you want to do within it? And I think we want to lean more towards the latter.
**Rahul Sonnad** *[05:37]*: Yeah, well that can happen with that. People from the first category. People that. Oh, you already have your thing. Why don't you. That looks good. Did you cut a little bit of the. No, were fine. That was beautiful.
**Rahul Sonnad** *[05:51]*: Yeah, didn't cut it, but it like it's cut off cuz it's behind here.
**Sonia Wendorff** *[05:55]*: Yeah, yeah, that's fine. That was pretty good. Okay, next question. What kind of demographic do you imagine coming to Spanic Gardens? What kind of people are we looking for? Because you mentioned Soho House and it's a great model. I feel like it's a little bit of a different approach like Soho House. More prestige in group out group based on your social financial status. And I don't actually know if this is what we want, but definitely don't want like a bunch of hippies that cannot pay for anything. So what is the demographic that you imagine that would be?
**Sonia Wendorff** *[06:35]*: So, so I think the demographic will be highly informed by like where we do it and stuff. If were to do it at a college or something, I think there's an argument to say just do it with college students, you know, maybe a graduate or undergraduate or whatever. Like so it's kind of the community there.
**Sonia Wendorff** *[06:56]*: But that's a little bit of a challenge. Like I really like that model. I think it shifts the whole process very much. Like whether you do it with university students or you do it as a. As like a regular membership model because students usually don't have a lot of money and you might, which I know you mentioned you a little bit resistant to plug into governmental funding. If this is an offering that is going to benefit students and there's going to be some educational programs around food production and tech like that, I think we could definitely get a lot of funding for that. But you mentioned I don't really want to deal with the restrictions.
**Sonia Wendorff** *[07:35]*: Yeah. In general, I mean the thing is money is so cheap and plentiful now. So the question. And like if you're doing the right thing and I think this is the right thing. I don't think it's the right thing for everything, everybody. But I think it's the right thing for you know, 5% of the funding market or whatever, which is a huge amount of.
**Rahul Sonnad** *[07:54]*: So how would you expect students that probably do not work to pay for a membership?
**Sonia Wendorff** *[08:01]*: I don't know like when I go to Core Power there's all these like students taking $150 a month membership. Like student membership.
**Rahul Sonnad** *[08:11]*: Yeah, some people are just. Yeah.
**Rahul Sonnad** *[08:14]*: Privileged. Seems to be no shortage of that.
**Rahul Sonnad** *[08:16]*: But I think it's a different demographic because most universities in Poland are public universities. You don't actually pay for them so it doesn't identify your financial status and you want to make it like accessible.
**Rahul Sonnad** *[08:28]*: It's a public university too. But anyway, like the thing is. The actual short term profitability is not super important. The visibility into medium term profitability is important. So. So like if you could have something that's really like vibrant with student and it works and they're just loving it and let's say they're paying $20 to come for an evening. €20. And I think people can afford that. Like people can come, you know, a couple times a month for €20. That's not like some elite group or anything. I mean that's the same you'd pay to go see, you know, to.
**Rahul Sonnad** *[09:24]*: Yeah. As a student. I used to be a student and I can imagine in today's money like you say 20 Euro. 20 Euro sounds a little bit better than 100 Polish dalty. If I were to pay even 50 for an evening and I was working, I would be like, that's some bougie.
**Sonia Wendorff** *[09:42]*: Yeah, but that's a different time when you're a student.
**Rahul Sonnad** *[09:44]*: Yeah. What do you mean different time? But I'm saying 50 would be 50. That would be 50% of the current price. 50% Of the what price of that 20 Euro. What I'm saying, I'm imagining I'm paying like 10 Euro at the time when I was studying.
**Rahul Sonnad** *[10:01]*: Yeah, yeah.
**Sonia Wendorff** *[10:02]*: So and I would be like, but it's quite bougie.
**Sonia Wendorff** *[10:06]*: Like if you can create really good product for students at 20, I think everybody will be like, yeah, you can create good product for older people at, you know, 40 hero or whatever. So I, in general I feel like we'll do better like with the 25 to 45 demographic, like so working people. Yeah, we're a little bit more mature, a little bit less have like college is such a networking availability that. And when you leave college you have less of that. So like if you, it's what we provide is a little more scarce amongst an older demographic versus amongst college students. Yeah, for sure. I think it would be interesting to have like to test out a college event where we just get college students, you know, and do one event targeted at those people or something.
**Rahul Sonnad** *[10:58]*: Yeah.
**Rahul Sonnad** *[11:00]*: But I don't have a good, like my just, you know, first blush intuition is 25 to 45 year old people who are like tech forward, creative, health focused, you know, into music. So people who would go to fitness classes, who would go to DJ events, who would go to, you know, who want to learn that type of thing. But I don't feel like I have a, especially in Poland, a good enough sense of the demographics and what people are into and how that makes us and stuff. So I think a lot of that we're just gonna have to try to experiment and I think we can, you know, try different targeting for week one versus week two versus week three. We can have different themes and things like that. Like it, I mean we'll have the sponic theme.
**Rahul Sonnad** *[11:57]*: But we can have other, you know, based on who the maybe speakers are or something like that.
**Rahul Sonnad** *[12:03]*: Yeah.
**Rahul Sonnad** *[12:04]*: So. Yeah. So answer.
**Rahul Sonnad** *[12:09]*: I don't know. Yeah. Okay. Well, I. I agree with you. I feel like. I don't know, there's something really interesting for me in the university concept. I feel like it's a lot of impact and something really needed. And so students can take a lot of value. Maybe not the social value, but the value from being around inspired people and being exposed tools that are gonna set them up for successful future. But yeah, I feel like a little bit older people that already have, like, some idea of what path they want to take and less social opportunities and probably a job might be a better demographic.
**Sonia Wendorff** *[12:52]*: Yeah. I think there's a higher chance that just doing students, like, won't work for some reason. And there is. That it'll work so much better. Like, Facebook obviously started with students.
**Sonia Wendorff** *[13:04]*: Yeah.
**Sonia Wendorff** *[13:05]*: And that worked out really well. But then it was clear that, yeah, this can apply to anybody pretty much. But I think the whole. I think this will be more like. Like Facebook could house all the same people on the same exact platform and it would still all work. And I think this will be harder to do that like, you. You need a homogenous group that has some strong commonality in the beginning.
**Sonia Wendorff** *[13:44]*: Yeah.
**Sonia Wendorff** *[13:45]*: Now again, that could be like, I think you could totally do this in Alabama with Christians.
**Rahul Sonnad** *[13:50]*: Yeah. I mean, you can do anything. This is a great project. It's called Act Real Estate. And they developed this concept for Ranchise, which is like franchise but for ranch locations. And I believe they're only successful. And they had, you know, enough people to keep it going is because they're like Christian focused. And it just like, it's like most people don't have the ability to assign value alignment with other people. They just never think in these terms. And so knowing somebody else's religion is aligned with yours is enough of a signal that like, okay, this is the way I want to live my life. I feel like we should have our own religion.
**Rahul Sonnad** *[14:34]*: I can be.
**Rahul Sonnad** *[14:40]*: Okay. On next question, something that I'm thinking about now that you're talking is what is the actual value that people will be getting from being participating in events as parent gardens and assuming there's going to be different, like, variety of different events that focus on movement and botanical cultivation and again, send the social connection. But I think super impactful and also quite easy since you're already setting up all the infrastructure with AI is having workshops around that, like, use of AI, use of technology, which I can really see on the side. But I'm looking at Frontier Tower and like, this is pretty much all the events that are happening around that, like around vibe coding and like connecting AI and digital tech to hardware and such. And it's just something that people are really interested in.
**Rahul Sonnad** *[15:37]*: Yeah, I mean, I think let's assign just percentages. They're not exact or anything, but I think like 50% of the value is the stuff you're doing. Oh, I take a sauna. Like, what's the value of a volley? I'd say it's like 90%. You're in the sauna and you like being in the sauna.
**Rahul Sonnad** *[15:58]*: There's naked people, nobody uses their phone. That's like pretty much the secret. And it's beautiful inside.
**Sonia Wendorff** *[16:04]*: Yeah, I think, yeah, the fact that you're forced to detox digitally is good,.
**Rahul Sonnad** *[16:12]*: But that's not going to happen. That's funny because you're gonna get overwhelmed with digital infrastructure.
**Rahul Sonnad** *[16:19]*: We do weird things. Like we can have one jam the cell signals. So you only have like local WI fi.
**Rahul Sonnad** *[16:28]*: I think that's pretty amazing. I mean, it seems a little bit hypocritical. Maybe if you're like, you can.
**Rahul Sonnad** *[16:39]*: Well, I think you can maybe do that for the sauna area or for certain events that are non digital. But anyway, the point is like 50% of the value I think is all the things you might do. So it's either saunoing or taking your yoga class, or doing the dance or doing the music event or whatever. So those in aggregate or 50%, and then 50% is just the serendipitous social nature of it. You're meeting people, you're connecting, and it's really the other people providing you the value. Yeah, like, here's a place where I go to see these people who are amazing and hang out with them.
**Rahul Sonnad** *[17:22]*: And I think in order for that to work, like, the clear way that works is if you get like anytime you get collections of great people, whether it's like at a company or at a conference or whatever, they just create value for each other through the connections and everything. And the conference organizer is typically not doing that much. Like, I mean, if you look at any conference, it's like, okay, they book the space, they kind of, you know, sell vending, they sell speaker slots, they give away some speaker slots.
**Rahul Sonnad** *[17:55]*: But, well, I think it's slightly different because usually conferences are around a specific topic and that removes the barrier of like, oh, it's a random person that I don't really know what they're doing.
**Rahul Sonnad** *[18:05]*: Right. Yeah, I think that's right. So there's a theme to conferences and I think we need to have,.
**Sonia Wendorff** *[18:19]*: Hey, Alexa, turn the lights in the dining room yellow.
**Sonia Wendorff** *[18:28]*: Alexa, set dining room lights to 100% soft white.
**Sonia Wendorff** *[18:36]*: I'm not quite sure what went wrong with the dining room. This fun and garden beyond, mind you.
**Sonia Wendorff** *[18:49]*: Yes. So I think the more like specific events can be themed and I think AI is a good theme. Obviously. I think there'll be a lot of interest in that and that'll kind of, you know, be relevant to what we're doing versus meditation.
**Sonia Wendorff** *[19:07]*: Right. Because I feel for a lot of people it's a little bit challenging to walk into a space and make conversations out of nothing. So if that is facilitated, like if we already have some data about these people, then we can like do speed networking or.
**Sonia Wendorff** *[19:23]*: Though my thesis is if you do pre speed networking, meaning you get a 15 minute interview from the AI on telephone before you come in, then you can start making these connections in a way that's never been possible before. So that I think is like something we want to try to prove out. Like, can we, you know, do a much better job at speed networking and figure out, like, what do people really want to network against? Like, is it jobs? Is it social? Is it, I'm not sure what the most. Like when you take, if you have some very specific theme, then clearly people want to, you know, network against that theme. That's why they're there. But if you have a less specific theme, then my question is, okay, what do people really want to be?
**Sonia Wendorff** *[20:22]*: I feel like everybody just needs an accountability body. And if you're, if you already have online where you're looking for like some sense of compatibility, we can just match people based on that and they don't necessarily need to exchange services. The only services being bodies around the top.
**Sonia Wendorff** *[20:40]*: Yeah. And I think you could, yeah. Have, you know, if an event starts at the same time, you could pair people up in pairs first and one person's been there a bunch and the other person is new and then there's some protocol and then it switches. And I feel like that's the real like kind of product management magic that we need to try to figure out. And I, I, I feel like the only way to figure that out is through trial and error and like iterations. I mean, you can have theories, but I don't think they're worth much until you prove them to be right. Yeah.
**Sonia Wendorff** *[21:45]*: Okay, Another question about grants and governmental funding.
**Rahul Sonnad** *[21:52]*: Yeah.
**Sonia Wendorff** *[21:52]*: Can you expand on. You mentioned to me that just the restrictions that come from fulfilling the deliverables that you outlined, like, months prior to actually receiving the money is restrictive. Is there anything else that would be concerning for you?
**Sonia Wendorff** *[22:15]*: Claude can do it almost.
**Sonia Wendorff** *[22:18]*: I kind of like it that way.
**Sonia Wendorff** *[22:28]*: I didn't understand the question. Like, what? With regards to grants and government money.
**Sonia Wendorff** *[22:34]*: Yeah. Like what. What's your. What's your concern?
**Sonia Wendorff** *[22:38]*: 1.
**Sonia Wendorff** *[22:38]*: I already know the restrictions.
**Sonia Wendorff** *[22:41]*: Yeah. The general concern is. It can take a lot of time to get the money. You have to kind of be doing exactly what they want to be done. Usually grants are like, we're giving money for this. It's not like, tell us what you're doing and we'll give you money for that. Whereas, like, venture funding's like, you have an idea, we like it, we're going to give you the money, and we're not at all telling you what to do. We're backing your idea exactly as you have been. Now, some VCs try to steer you one way or another, which you generally want to avoid. And the really good ones kind of let you do your id, but steer you a little bit so you do it right.
**Sonia Wendorff** *[23:25]*: But, Yeah, I just think there's much less flexibility and then there's like, weird considerations that you have to care about because the government, I don't know, let's say you have a naked sauna or whatever. Maybe in some governments, they're not going to be down with that at all. I think in Eastern Europe it wouldn't be a big deal. But, you know, so there's, like, criteria and things like this and that just get in the way. So the question is, why do you want the government money? Like, if it's a grant, you can say it's basically free money. So I'm not giving away any equity, which is better. So I'm not, like, totally opposed to grams. It's just that, like, it feels like for the effort you put into either getting grant money or private money.
**Sonia Wendorff** *[24:23]*: Yeah,.
**Rahul Sonnad** *[24:25]*: My sense. And again, I haven't been in the fundraising market for like, five years or something, so I'm just kind of watching on Twitter and saying, wow, this looks crazy. People are just splashing money all over and everybody's like, I've got 150,000 to give away. My DMS are up and let me know, you know, And I don't think there's that many good companies. Like, so I think, like, for the San Francisco investor, I think we have a lot going for us. Because a. I think the idea is actually really interesting. It's different from everything else. Like there's not three of these that like there's like no other, no one else is going to pitch anything like this to anybody like AI like in the next year. So it's kind of like, okay, I haven't seen that before.
**Rahul Sonnad** *[25:14]*: Which a lot of people are really big on. Like, you know, you got to invest in something other people aren't doing. And then if you think about it, yes, this is a very scalable idea. If Soho House can become a billion dollar company on not really any tech or anything like that, just kind of sales and marketing, this is much more interesting. I think it's defensible. This can't be replicated by a foundation model company, which is the big worry everybody has now in their funding. And then I think I have enough experience where you know, it's not like 100 positive, but I think like I can convince people that like I'm not gonna make any button headed decisions.
**Rahul Sonnad** *[26:08]*: And I think, you know, you being Polish is gonna make it feel like if, if it's just like an American going into some foreign country to do something. I think you'll get a lot of skepticism. So I think like, Yeah, I think it's very like fundable now. It's hard to tell like until you actually get like real feedback because you never know, like actually worries people and it might not be obvious, but. So the point is that I think you have the cheapest venture capital in history available as readily as possible. Which doesn't mean it'll be like easy to get it, but it's like, you know, you'll do 50 pitches and you'll get it, but. And you might get a lot. I think you could also like, there's kind of no like for first rounds now.
**Sonia Wendorff** *[27:10]*: People do anything from like a hundred thousand to you know, literally $100 million like for AI companies. I mean this wouldn't warrant more than like I couldn't imagine taking more than $5 million in the first round. Like I don't know what you did. So. But $5 million is nothing for these companies. Like they will do that with the understanding that there's a 80% chance of entire loss of this like in two years and they're fine.
**Sonia Wendorff** *[27:43]*: Okay.
**Sonia Wendorff** *[27:44]*: You know, so. So it just seems like I just worry that there's like bureaucracy with grants and governments and that you get.
**Sonia Wendorff** *[27:54]*: Yeah, I mean there absolutely is. And Then you assuming that we're going to be testing and you know, changing and testing and changing.
**Sonia Wendorff** *[28:01]*: Yeah, that's the other thing. Like if you want to in like three weeks, completely change the plan with private investors, you just go to them and say, hey, this isn't working, we're switching. And they could be like usually like okay, yeah, that makes sense, go ahead. Like you know, or you know, they may be like, well that's not what I signed up with, you know, for something like, I mean, I think we can't switch to like, you know, weapons, you know, company or something like that, but like you know, target markets or anything or get rid of the plants or you know, make it more thematic or make it college focused. Only like any changes like that would, is not going to phase anybody. Whereas if it's government, I feel like you never know what's gonna face them.
**Sonia Wendorff** *[28:53]*: But I, I'm not opposed to it. And if there's like stuff available, I mean we can just put Claude on it and ask for a go find all the grants and go.
**Sonia Wendorff** *[29:03]*: I really found a bunch. But yeah, I feel like most of them come with restrictions and yeah, I.
**Rahul Sonnad** *[29:09]*: Mean if they don't.
**Rahul Sonnad** *[29:10]*: But it's also fairly easy now. Like I, I didn't do that with cloud, but I believe you can do it so easily in the past you have to have a specific.
**Rahul Sonnad** *[29:20]*: I think, I think applying to those now is going to be like super simple because we'll just basically have cloud apply to them. So it might be you just hire a, you know, €20 an hour intern and have them apply to a bunch and see what happens. And maybe it takes a year, but that's fine, you get $500,000 in a year or something for free. But, but I feel like shouldn't be like the strategy, it should be like an add on. Nice to have.
**Rahul Sonnad** *[29:56]*: Okay. That we kind of already discussed. What spaces do you want to prioritize and like physical infrastructure wise, what amenities are priority? Like you have spot there. How big of a priority is that? Yeah, like name essential amenities and yeah,.
**Rahul Sonnad** *[30:39]*: I think, I think you want to start off with like very low cost, quick. Like you want to be able to get it up and running in two weeks.
**Rahul Sonnad** *[30:49]*: Yeah.
**Sonia Wendorff** *[30:50]*: And to do that, I think the really simple thing is it's like a, you know, kind of multi table tea surface type of thing. So it's food, like light food and beverage, music. Good, like video screens and stuff. So you can have subtitles, you can project things, you can see things good audio Equipment, like so microphones, that type of stuff. And I think that's probably enough, like, I think that gives you enough to have like a really good event. And then like, with more time, I feel like you want to have saunas by the time it's winter in Poland. You know, sauna, hot tub, plunges. And I think that's pretty cheap. Like, that's. I think you can whip together like a sauna like this very quickly. Like two guys.
**Rahul Sonnad** *[31:59]*: Yeah.
**Rahul Sonnad** *[32:00]*: Can do that in like two days.
**Sonia Wendorff** *[32:01]*: Yeah.
**Sonia Wendorff** *[32:05]*: So I think that's pretty easy to put together. And then you need like, well, before you have that, you need like rain sheltering and stuff. You can probably in summer get away with outdoor. Like, I don't know how. You gotta kind of look at the weather forecast and say, okay, for the event, do we need a big sunscreen or.
**Rahul Sonnad** *[32:30]*: Yeah.
**Rahul Sonnad** *[32:30]*: Can we just do it out in the open or. But eventually you need like rain protection and everything.
**Sonia Wendorff** *[32:35]*: Yeah.
**Sonia Wendorff** *[32:36]*: So, like, let's say we partnered with. How do you say most? Most.
**Rahul Sonnad** *[32:41]*: Most.
**Rahul Sonnad** *[32:42]*: Yeah. Like, if you partner with them, I feel like they've got just tons of land all over. Like they've got, you know, 14 acres or something. So it's like almost 10 times as big as this and they're not really using it all. So we just figure a place and we just start building there. We're going to need, obviously electric. We're going to need Internet. I think I'll take the Starlink. So we don't have to. So we'll have local Internet. Maybe I should get a big Starlink. That's probably fast enough. So. Yeah, I think that's all you really need. And then you want it. I think you want to kind of decorate it really nice and just make it like.
**Rahul Sonnad** *[33:29]*: Yeah. Like it's super cozy.
**Rahul Sonnad** *[33:31]*: Beautiful and cozy. Yeah. So like, when you go there, you don't. You feel like, oh, this is. And like lighting.
**Rahul Sonnad** *[33:38]*: Yeah.
**Rahul Sonnad** *[33:41]*: Though if we do it in the daytime, lighting's probably not that important.
**Rahul Sonnad** *[33:44]*: Yeah. But coziness still is.
**Rahul Sonnad** *[33:46]*: Yeah.
**Rahul Sonnad** *[33:47]*: Being. Yeah. And being comfortable for working, like ergonomic, like for people hanging out. It can be like floor seating spaces and. Or like, you know, couch set up, the cozy setup. But you definitely some sort of court.
**Rahul Sonnad** *[34:08]*: I think there's a separate issue of working where, like, there's kind of the event space. And then I think we need a separate workspace. Like eventually they should all be just the same thing. But I think to start out with, you know, maybe we're working from a house or something and Then we're doing the event somewhere else and sometimes we'll have to go on site and set up there and stuff.
**Rahul Sonnad** *[34:31]*: Well, I'm thinking more about members because things like co working space brings a lot of value to people without us having to facilitate a very structured thing. Like we want people to be able to come and work and interact and, you know, log maybe having like an AI accountability corking session.
**Sonia Wendorff** *[34:55]*: The challenge though is to build co working in the middle of nowhere. Like. Like on a farm. Yeah, is.
**Sonia Wendorff** *[35:04]*: But it's not actually the middle of nowhere. Like if we're thinking about mos, but most of the location there are like.
**Sonia Wendorff** *[35:11]*: Yeah, I don't mean the middle of nowhere, but in a. In a farm. In an urban farmland area where you don't have structures. Yeah, you like to do co working. You kind of need, you know, certain quality of electricity and you need interior. Like because you don't want all the computers to be like outside all day and stuff. I mean, you could have like a. And you need like certain lighting. Otherwise you can't see your computers. Like if it's bright outside, you can't just co work outside. Like, maybe there's a building there that they're not using that we could take over and make that the office. That would be ideal. And it's close enough. Like, you know, it's a 10 minute walk from the area where we're doing the actual, you know, event venue.
**Sonia Wendorff** *[36:01]*: And eventually we'll want to build on to the event venue. But that could require permitting and everything like that. I think setting up tables and stuff is not going to require any permitting. Yeah, so. So I think we need, you know, one space for the events, one space for working. The closer they are, the better. But I don't think they're necessarily the same space.
**Sonia Wendorff** *[36:25]*: No,.
**Rahul Sonnad** *[36:45]*: It.
**Sonia Wendorff** *[37:14]*: That was good. Are you gonna put it in your room? No, I feel like if you have a little. A little Grateful Dead altar, like you have one for Elon Musk.
**Sonia Wendorff** *[37:28]*: There's one, I think, isn't it Grateful Dead? Right. Playroom. So go and check poster. I think there is. Yeah, it's. Yeah, that could be the great. It.
**Sonia Wendorff** *[38:53]*: Fr are down. Cuz Joe is not coming here. So what's the story of Jackie? Jackie just like foster work until the situation is resolved? Or did she communicate with you like, hey, I'm quitting? Like, what?
**Sonia Wendorff** *[39:19]*: She's quit. This is her second time.
**Sonia Wendorff** *[39:23]*: Okay. Also because of before.
**Sonia Wendorff** *[39:27]*: She was quitting just because she wanted to do something else. But then I think she couldn't Find something else. So she came back, I suspect.
**Rahul Sonnad** *[39:37]*: But, like, the only reason she's not.
**Sonia Wendorff** *[39:38]*: Coming is I think at this point the only reason was the situation. I. I think that situation's resolved. I don't think there's any issues anymore. So.
**Rahul Sonnad** *[39:54]*: Okay, more questions. Not many more, but brace yourself. Okay, so the same thing as with amenities like physical infrastructure. What are the elements of the AI infrastructure that we're going to prioritize?
**Rahul Sonnad** *[40:19]*: So AI, there's like a lot of. And it's kind of complicated.
**Rahul Sonnad** *[40:28]*: Well, you already mentioned a monitor. So there's some, like, software and hardware responding to, like, feedback and conversations.
**Rahul Sonnad** *[40:36]*: So I think there's like a set of things, like there's devices. So you've got. You've got. Just like here you've got all the devices. And some of the devices are like monitors, like summer sensors. Summer. You know, some are input, some are output. So monitors, speakers or output microphones, sensors or inputs. Cameras are inputs. Camera DJ is an input output combination, patentable. And. So that's devices. And then you want things like CNC and 3D printers and things like that, which would be outputs. Then you have, You know, membership and marketing, kind of CRM, like customer relationship management. And it's kind of CRM AI.
**Rahul Sonnad** *[41:49]*: So it's something that interviews every member and creates a profile on them and then starts, you know, vectorizes that and starts using it to match people and ask people, like, what they want to offer others and what they're looking for and what their interests are and all of that. So there's going to be a whole kind of big system there. And I think that's kind of a lot of the core IP to make that both. How do you gather that? How do you make it work? How do you call them on WhatsApp? How do you let them leave voice messages? And luckily, I think, like, openclaw solved most of that, like, because they have the connectors to all these various, you know, telegrams and WhatsApp and what have you. If we can ever get a WhatsApp business account.
**Rahul Sonnad** *[42:38]*: And then, and I think kind of somewhat separate than that is just general marketing. Like, how do you market. Then I think there's the building. How do you actually build out things and design, you know, doing the design, kind of like the renderings here of the place. Because I think you want to be designing like the next months collaboratively, like every. You want to just always be deciding the next two months what are you going to be building. Yeah, and that's like a very different type of thing. And then you need to teach people how to build it. And that'll include, like, making orders. Like, there's. I assume there's like the Home Depot of Poland. I don't know what it is, but you know, the big hardware store. And so you're gonna have it automatically order everything. And.
**Rahul Sonnad** *[43:29]*: And similarly with food and drink, you're gonna. Whoever the vendors are, you're gonna have it automatically order that type of stuff. Now you won't need that for the first month or two or something. You can just go buy it. But like, the goal is like, all of that's automated. And then there's like kind of educational things where people say, like, what topics do you want to learn about? And then, you know, the AI will put that together and maybe even like source an instructor or something like that. You know, reach out to people, send out emails and say, hey, here's what we're looking for. So that's kind of like. It's kind of like marketing, but it's marketing for. Not for membership. It's marketing for facilitation. And then there's the whole commerce piece of it, which is like food and drink vending.
**Sonia Wendorff** *[44:33]*: And how do you get that set up? How do you. And that'll be like a subset. Like, there'll be food and drink marketing, which is like on site and on app, which is very different than the membership marketing, which is going to people who haven't been there. So they're kind of analogous, but they're different. And then there's, you know, the whole feedback system, which is a little different than CRM because that's more about the facilitation side of things for the events and the activities, getting feedback around that. And then there's just a bunch of, like, corporate stuff that needs. I mean, some of that's already put together. I mean, I feel like there's a lot of.
**Rahul Sonnad** *[45:29]*: Between the Alpaca Playhouse site and the spa garden site, like, if you can plate those and like, kind of productize them now they're just kind of a little bit too rough around the edges and untested and what have you. And there's no test framework or anything like that. But if you take everything there and really productize it, I think you've got a lot to deal with. So there's all the membership management, billing, all of that, which is kind of like CRM. Yeah. So I think those are the main things.
**Rahul Sonnad** *[46:03]*: And which ones do you find all of them to be a priority in the very beginning no. Which ones? Like the most prevalent in my.
**Rahul Sonnad** *[46:18]*: I mean, I think the only one that really matters. Well, you have to have some website and everything and that's already done in AI, so I'd say that's a priority. It's not. There's not much incremental work. But then the next one is like the CRM. The CRM is the important one because it's about the people who are coming. How do you get deep with them in AI? And then I think there may be like a separate. Like what I definitely want to test is like events where everybody's mic and talking and such and they know they're being recorded and such. And it's not for the whole event, but for like this half an hour we're going to do like an AI section that's being recorded and then see what comes out of that, like what the AI can.
**Rahul Sonnad** *[47:09]*: How many mics do you have right now? I don't think we actually need them, but we should have like at least five person dinner here in the next two weeks where we just test that.
**Rahul Sonnad** *[47:21]*: Yeah, I only have two mics, but I mean those are pretty cheap. They're like.
**Rahul Sonnad** *[47:25]*: But I also feel like it's. It's not like we're so far away from each other. It's gonna be a small group of people. So it can just do voice recognition.
**Rahul Sonnad** *[47:33]*: That's hard to do. Like what I've read is like the voice recognition amongst a group of people is very hard versus if you have a mic for each person, it'll automatically, you know, you just say this is.
**Sonia Wendorff** *[47:44]*: That's interesting. My Fireflies is doing a pretty good job but like sometimes makes a mistake. But usually it's like Speaker 1, Speaker 2, and then you know, based on.
**Rahul Sonnad** *[47:52]*: The context on Zoom or not.
**Rahul Sonnad** *[47:55]*: I mean you can put it on Zoom, but you can also record it from your phone. Yeah. Have you used Fireflies? Yeah, I think it's like Whisper.
**Rahul Sonnad** *[48:03]*: Or we could test that, but. But anyway, the mics are cheap enough that, you know, they're 40 bucks a piece or something, so they're not, you know, we can buy 20 of them or whatever.
**Sonia Wendorff** *[48:16]*: Did you learn how to use them? Did you take one to the concert?
**Sonia Wendorff** *[48:20]*: I did, I took one to the concert. I think I lost one key, like little USB C thing. Then I recorded it and it sounded horrible. It was like the worst recording.
**Sonia Wendorff** *[48:30]*: Really?
**Sonia Wendorff** *[48:30]*: Yeah. Well, I mean it sounded much better. Just the speaker out of my Android thing. Okay. That was also really high when I listened to it and I'm like. Maybe I'm just like, not hearing right. Listen it again.
**Sonia Wendorff** *[48:46]*: Like, when you went to other concerts, you were doing mushrooms. How much of the mushrooms would you be doing?
**Sonia Wendorff** *[48:51]*: Like, I don't know. I. I like. I did mushrooms at two. Yeah. Like one in Oakland, one in. In Nashville, I took a lot. And in Oakland we had some chocolate and we split it and I took it and I got pretty high. And the other guy, like, Rob just ate a big meal. He took it. He didn't feel anything. And Rick was kind of. So. But yeah, the first one in Nashville, like, super high. That's when I said I was like, switching into, like, different, like, templates of consciousness, like really quickly.
**Sonia Wendorff** *[49:29]*: Oh, yeah, that's. That's the trip that you told me about. Yeah, but that was after. That was after Nashville. I remember.
**Sonia Wendorff** *[49:35]*: Yeah, that was fresh. Nashville. Yeah.
**Sonia Wendorff** *[49:37]*: Yeah.
**Sonia Wendorff** *[49:38]*: Second shot. I just was like a little bit of cannabis notable.
**Rahul Sonnad** *[49:47]*: Do you always get high when you go to concerts?
**Rahul Sonnad** *[49:51]*: Always get high when I go to concerts, yeah. I wouldn't say always, but usually.
**Rahul Sonnad** *[49:58]*: Okay, that's.
**Rahul Sonnad** *[49:59]*: Wait, you mean high on campus or high on other things?
**Rahul Sonnad** *[50:01]*: I mean, just in general, like, outside of your regular state of consciousness, do you always seek to have some psychoactive substance?
**Sonia Wendorff** *[50:10]*: If it's like, dead? Ish. Yes. Cuz like, for me, like, dead is like the perfect experience of when I, like. I feel like I'm just absorbing so much info and opening up some of the pathways with that type of music. If it were like, in a different type of music, I wouldn't so much like with Pearl Jam. Less so, though. I've done a lot of drugs with Pearl Jam, but, like, I feel like I've seen between Pearl Jam and any better, like 50 shows or something. And I've probably been high like 20 times or something, not like 40. Like, for the dead, like, stuff. I probably. The thing is, if they're three days in a row, you can't really get high holidays.
**Rahul Sonnad** *[51:00]*: So, like, you could probably gonna.
**Rahul Sonnad** *[51:04]*: Like, many have tried and many have failed.
**Rahul Sonnad** *[51:08]*: How did the assay make you feel? Because you took like 1.7 finally. I took one and a half. That was pretty high.
**Rahul Sonnad** *[51:16]*: I felt by the end. Yeah, it was pretty high.
**Rahul Sonnad** *[51:18]*: Yeah.
**Rahul Sonnad** *[51:19]*: But. But then I also took like the mdma.
**Rahul Sonnad** *[51:22]*: Yeah.
**Sonia Wendorff** *[51:24]*: Which I felt like was really weak. Like, I. Like, I barely felt it. Like, it was. It was very subtle. Like, I felt like, emotionally, like more open and everything, but I didn't. I didn't have that, like, MDMA buzz. You never took the MDMA with Tommy, right? No, when he was here either.
**Rahul Sonnad** *[51:45]*: No, I don't want Tommy to check my buzz, that's for sure. I mean, I would be open for it. But in general, like, it didn't feel like a sen.
**Sonia Wendorff** *[51:54]*: I kind of feel like he gave me that and he gave me the syringe. And the syringe was a really short needle.
**Sonia Wendorff** *[52:02]*: Yeah.
**Sonia Wendorff** *[52:03]*: And I kind of feel like it didn't get in to the right place.
**Sonia Wendorff** *[52:07]*: But he gave it to you during his birthday party?
**Sonia Wendorff** *[52:12]*: Yeah, right after. Yeah. I mean, I didn't take it then, but I had the syringe.
**Sonia Wendorff** *[52:16]*: Did you just do the syringe now at the concert?
**Sonia Wendorff** *[52:18]*: Yeah.
**Sonia Wendorff** *[52:20]*: Took the syringe with you or did you have it?
**Sonia Wendorff** *[52:22]*: Where did I have it?
**Sonia Wendorff** *[52:23]*: Yeah, like did you have it in your bag? Cuz they searched through my whole bag and when I was standing in line when you went, I just repacked it to mine.
**Sonia Wendorff** *[52:30]*: Yeah, I, I, I have a special pocket in there that's like in the inside, except like nobody ever finds it. And it's like a tiny syringe. It's like at the very bottom. But he did go through everything. Like he was very thorough.
**Rahul Sonnad** *[52:44]*: Yeah. I mean, what would they do if they saw a syringe?
**Sonia Wendorff** *[52:48]*: I'd just say it's my insulin, you're not gonna test it or anything? Like.
**Sonia Wendorff** *[52:54]*: Yeah, okay.
**Sonia Wendorff** *[52:58]*: But I felt like by the end I was like by the time we moved down to the front, by the second time, you know, not to the very front, but like to kind of. Yeah, were like six or seven seats back in the front, but like were there in the beginning and then we came back. Yeah, I remember by that time I was like really high. Yeah, like prior to that it was like not.
**Sonia Wendorff** *[53:21]*: Yeah, you were saying. I think it was like a little bit less powerful. But yeah, at the end of the day I was pretty high. Like it was very aware of everything that's happening around me. It was like a good level of high.
**Sonia Wendorff** *[53:32]*: Yeah, a really good level. Like I wasn't too high, I could think I could manage, but it was still like just perfectly intense. Like it didn't need to be anymore.
**Rahul Sonnad** *[53:41]*: But like, how do you. That was kind of my question. How do you compare that feeling of acid to mushrooms?
**Rahul Sonnad** *[53:53]*: Like with the mushrooms I felt like much more like I don't know what's going on and like how's the universe work and this type of thing. Whereas like with the acid it's just like cool, intense, like. Yeah, like you know, but it's like, nothing. Like, I'm not confused at all about anything. Whereas, like, with the mushrooms, It's like a much more, like, conscious, like, crazy experience. And like. Like, in all these, like, hallucinations of sounds and actions and activities, really, like, I felt like. Like the whole thing was like an AI, like, programmed thing. Like, clearly part of me is like, no, that couldn't be here. But, like, part of me was like, yes, it is. I can. So just like, it was weird.
**Rahul Sonnad** *[54:51]*: I feel like I should try mushrooms again. I. I don't remember when was the last time. I just love acid so much that anytime I decide to do drugs, I just. I'm totally satisfied with acid. I feel like mushrooms are more of a bodily sensation for me, and I often get, like. I don't know. I guess they're, like, much more overwhelming. Okay. Priorities.
**Rahul Sonnad** *[55:20]*: So, yeah, the priorities are really, like, the CRM. Getting people seeing what connections you can make. And, like, we have to get, like, some things that, like, amaze people, where they're like. It's like, once in a while they ask Claude to do something. Wow, that's so cool. Like, we have to have that kind of feeling for what the AI is doing for people and connecting them and with other people or in the context of other people. Can I think of them with relevant things to talk about or.
**Rahul Sonnad** *[55:53]*: Yeah,.
**Rahul Sonnad** *[55:56]*: And I think there's also a critical mass issue around that. Like, if you have a dinner party of eight people, I think that's going to be much less powerful than a room of 100 people where you can connect across, you know, to all the people.
**Sonia Wendorff** *[56:11]*: Yeah. Okay. Yeah. I think that's.
**Sonia Wendorff** *[56:27]*: What we talked about already. Did you record it all? Yeah. So you can just. Are you on the Spawnic Gardens project or just Alpaca Playhouse?
**Sonia Wendorff** *[56:46]*: I'm just Alpaca Playhouse.
**Rahul Sonnad** *[56:47]*: Okay. I'll, like, maybe tomorrow I'll connect to the Spawn Gardens. But you can. On either of them, you can. No Backup Playhouse.
**Sonia Wendorff** *[56:54]*: Yeah, transcripts.
**Sonia Wendorff** *[56:55]*: But, yeah, just upload the file and tell it to transcribe it.
**Rahul Sonnad** *[56:59]*: Yeah, I mean, it's, like, already transcribed. I'm using for things that I don't really need, like summary, and I don't need to send it. I just use voice memos, and it just gives you a text file of that. So that's. That's pretty simple. Okay, last question. Why me? I feel like a little bit. I feel like you can get a person that has more business experience than me. I don't really want to question it. I Feel like I have the capacity.
**Rahul Sonnad** *[57:36]*: Yeah, the number one problem with startups, I think literally like the number one reason they fail is like the founders get in big fights over things and like just don't work out together. And like, I think we've known each other long enough. Like I think there's like a very low chance that we'll get into like a company destroying fight over like what we're doing. Like I feel like I could just like trust you to do anything both from kind of a competence perspective, like if you're pitching somebody or from just a, you know, keep like. Like I think with founders often there's a little bit worry of like, oh, backstabbing or power grabbing or something like that. Like that often comes to play. But like it's really hard.
**Rahul Sonnad** *[58:40]*: Like usually with Y Combinator, like they want you to have worked together for like at least like two years or three years or something because there's so many people they like come together and they just don't work out. And I'd say I have a high. Like a lot of people I would hire at my company, they seem great and they talk great and everything and then they just wouldn't actually work out for a variety of reasons because often because they talk, they can do something and they portray themselves as being able to do something. It's really hard to test people until they actually try it.
**Sonia Wendorff** *[59:18]*: But yeah, so I think like to me that's just having like trust and stability and you know, kind of a. I think neither of us, like if this all goes to hell, like it's not going to destroy either of us or anything. Like, I don't think it takes it like overly serious or underly serious, you know, so you've kind of got to have the right disposition and just be able to like laugh at like stupid things like Chelsea,.
**Sonia Wendorff** *[01:00:03]*: Which by the way, I really love what you did. Like this is amazing. Like I've been dreaming about it for a long time that everything just like high surveillance in the community. So people cannot get away with like random stupid shit that they do all the time, like stealing people food. But also conflict resolution is one of the things that you like emotions get involved and people just, you know, if it's not recorded, like if it's in text, we already have the ability to process it and people take screenshots and send it to their friends. But just having this like objective party that's AI, that is fed values of a community and resolve, it is just absolutely amazing. I have to Upload my conversation with her just to, like, seal the deal on the. On the page.
**Sonia Wendorff** *[01:00:47]*: And I thought, like, I thought the one on Rachel's car rental was good. This one's better because it's more, like, more dramatic. Yeah.
**Rahul Sonnad** *[01:00:55]*: Yeah, for sure. And it's, like, really hardcore because it, like, analyzes her psychologically, but we're not doing that. So it feels amazing and it points.
**Rahul Sonnad** *[01:01:07]*: Out, like, all the hypocrisy of her website. Yeah, it's. That's been, like, one of my favorite uses of Claudic. Yeah. Then the other reason is I actually think you'll, like, do incredibly well with, like, interfacing with people. Like, I think you can inspire confidence. Like, I don't know if you saw in that thing. I think it quoted Monique, like, Sonia's, like, the most confident person I've ever met. I forget the phrasing, but it was something like that. But I think, like, you come off, like, instantly. And I noticed this exactly, like, the first time when you. It was after you came here for Mo's, but like, in that, like, first day or something, were doing Mo's, I'm just like, damn. She's like, just really like. Yeah.
**Rahul Sonnad** *[01:02:17]*: I've had other times when I talk to you where I think you can get a little bit too talkative, like, a little like. But. But. But I think, like, and I think fundamentally, like, the. For a project like this, it's not fundamentally a tech project. It's more of a vibe project. Like, you're selling the vibe of the place. You're not like, people aren't coming there for the tech or whatever. It's not like we need to out tech a bunch of other places. We have to have, like, this weird, subtle vibe that works for everyone. And I. I like, believe you can do that as well as anyone, like, to figure that out. And. And then, like, you're Polish. So that's like, if I'm gonna go to Poland.
**Rahul Sonnad** *[01:03:28]*: Yeah. I mean, it definitely.
**Rahul Sonnad** *[01:03:31]*: I don't think it would work to. I. I think. I think a, like a female co founder would be much better and be a Polish co founder. So, like, you. It's rare to find a Polish person.
**Rahul Sonnad** *[01:03:53]*: Well, not in Poland.
**Rahul Sonnad** *[01:03:54]*: Yeah, but. But yeah, it would take. A while to find somebody. Like, and this is not that good. Like, the problem is, like, I'd find somebody, I'd try them, and probably it would take three people to actually find the right person. And then that's problematic for investors because they don't want you, like, cycling through Founders, it just feels like, oh, here's the founder. They're gonna hey his money. And then I also think, like, I wouldn't feel comfortable. Like, there's another, like, kind of truism and founders. And it's almost like, how do you split the equity amongst founders? And the answer is, like, you just make it even. Like, because it solves, like, 90% of your problems. And the problem you're worried about in not making it even is maybe, like, you're worth a little more on the market or whatever.
**Rahul Sonnad** *[01:04:53]*: So you should have more. Like, it just doesn't matter if the company does well. Like, you do really well. And by making it even, like, you double your chances of the company doing well because you're not having a big argument over equity. So, but that said, like, if I find some random person that I don't know who's not, like. Like, if they were like, a great AI engineer or something, like, you could say, okay, that makes sense. Give half. But just some other random person, I would be scared to do that. Because if they stay on and they don't leave, then they're taking a huge chunk of the company out. They may not be contributing at that level at all. Like, you may find out after six months that they're kind of lame.
**Rahul Sonnad** *[01:05:43]*: So, like, it feels really good and easy to say, okay, founders, you get half. Like, there is a weird kind of side thing going on where I'm also funding it. And, like, what I'm actually trying to do is to not to put less money in my pocket and put more in the trust pocket, because the trust will never be taxed. Like, for. Well, it will be taxed, but my tax situation is much more stringent than the trust. So if the trust makes, you know, $20 million or whatever, it gets to keep it. If I make that, it, like, it'll get taxed, like, 60% away or something. So. Say, yeah, in this case, because the trust's funding will get, you know, a piece of it. So it's not exactly equal, but there's also money. So it's.
**Sonia Wendorff** *[01:06:44]*: It kind of makes sense that when you put money and you get something for. So, yeah, but I think. I think we can. Like, we have very low conflict. Like, I don't remember many periods of conflict, and I think that's, like, one of the most important things. Like, you just don't want a lot of conflicts. Conflict between founders. It's fine to have, like, conflict over, like, should we do this or, you know, how this should work, and this is a good idea. This isn't like that type of conflict's fine, but like actual like personal conflict you don't want like.
**Rahul Sonnad** *[01:07:25]*: Yeah. Do you often find that you have personal conflict with people that you work with?
**Rahul Sonnad** *[01:07:31]*: Yeah.
**Rahul Sonnad** *[01:07:31]*: Why do you think that is?
**Sonia Wendorff** *[01:07:34]*: Because I just don't believe in the way they do things. Like they don't make sense to me and they often people like say they'll do one thing and then they don't do it and that creates conflict for me. Or they say they can do something and they can't do it or they say they're good at something and they're not. Like they have no self awareness of what they're good at. And like all of those just create conflict for me because I'm very like optimistic and like I want to believe like somebody when I hire them, they're going to be amazing and do everything well. So like I, I kind of have these blinders on and then when reality hits me actually see how they're working.
**Rahul Sonnad** *[01:08:15]*: Did you preserve that level of optimism after years of working with people?
**Sonia Wendorff** *[01:08:20]*: Yeah, I still am like very optimistic. But the thing is I'm pretty good now at identifying like usually within like a month of working with somebody, I can like now like clearly tell if they're good or not. And, and usually, I mean it depends what the situation is. It's one thing if it's like you know, somebody building the outhouse. It's different if you're like in a real like you know, kind of tech company type situation. But like in the tech company situation, if somebody doesn't work, you just give them like two months severance and tell them it's over. Like it's. And kind of do that quickly with no remorse or something. Like if you know they're not right for the company because it just doesn't help anybody to drag it on.
**Sonia Wendorff** *[01:09:18]*: Because like the key beyond like founder is not like getting into big fights. Like the next most important thing is just the next three hires. So it's like the first five people really I think are like 60% of either the success or the failure of the company.
**Rahul Sonnad** *[01:09:40]*: Yeah. Did you work with a lot of your friends, like friends that you were friends before you?
**Rahul Sonnad** *[01:09:51]*: I worked with a lot of like colleagues. So like when I started my first company to platform, I got three people I knew from Microsoft and three from Adobe and brought them all together and then it was like the seven of us and then a couple other like kind of low level people joined. So it's actually like eight or nine, you know, where we all started and were all like colleagues and you know, I'd say were friends and colleagues, you know, because you know, we hang out and have beers and travel around the world and stuff. In some cases at Microsoft did a lot of that. But so yeah, but they weren't like kind of originally social friends and then.
**Rahul Sonnad** *[01:10:35]*: Like, hey, you knew each other and work setting.
**Rahul Sonnad** *[01:10:37]*: Yeah. And then the same as like, you know, my, the second company. I didn't start with anybody because I moved from Seattle to la. I didn't know anybody. I just like walked into the vc, they gave me half a million bucks and then I just started hiring and you know, recruited people didn't know them actually maybe one guy was a friend, I'm trying to remember right now, And he actually didn't work out. He was running a product but he couldn't do it. But then like my CTO from my second gen company joined the third company and he brought his team with him and same like another guy from a company. I worked in the interim for a few months. Joined with me for the test loop. So yeah, there are several colleagues.
**Sonia Wendorff** *[01:11:40]*: Did you ever work with a romantic partner? No work engagement ever.
**Sonia Wendorff** *[01:11:49]*: Oh. So I met Kathy at a preschool. Like she was the teacher and I was like an assistant teacher, work study. So I met her there and then we moved to Oregon.
**Sonia Wendorff** *[01:12:02]*: Are you guys the same age? What's a whole.
**Rahul Sonnad** *[01:12:04]*: Yeah, she's older. She's like four years older almost twice. And then we moved to Oregon and she got a job at director of another preschool and then hired me and then she left and I became director because I was the only one with a college degree and they had a really like the director had different college degree for all these other teachers and I was like there for like two months and she left and they're like, okay. But it was like horrible pay. Like. Yeah, so I guess I. And it was fine. We were, we worked fine together.
**Rahul Sonnad** *[01:12:48]*: And you guys were together at that time? You were a couple?
**Rahul Sonnad** *[01:12:52]*: Yeah, were like, you know, we met while I was in senior of college and then we just stayed together after that. Yeah, but then after that, I mean, after that I was like, well then I, you know, kind of fell in love with my colleague a bit at Geodelic. I think I told you a bit about that. So weren't really romantic partners at all, but like there was some flavor of romance.
**Rahul Sonnad** *[01:13:28]*: Yeah. I'm asking because I just want to gauge your experience with like, I guess compartmentalizing different Areas of relationship, like working together and being friends and having different levels of involvement with each other. Like how well that's working out for you and has been in the past. That kind of answers my question.
**Rahul Sonnad** *[01:13:52]*: Yeah. Without him, like, were, I think were very much like, mutually in love, but, like, again, were like zero, like touching each other ever. And. But like, when were around, were just like, excited to be around. And like, everybody else got excited and we'd just go into any place and just sell them on anything because, like, there was like an energy and that worked really well. And. And like, it was totally fine. Like, like, so we once, like, early on in the company, like, she was the second hire. The guy I told you about was my friend was first hire. She was second hire. And you know Brock, He's like chairman of bitcoin based. He was one of the really bitcoin people. He introduced me to her and said, you should hire her. She used to date her. She's really good.
**Rahul Sonnad** *[01:15:02]*: But my interview was like, do you like any better? And she was like, yeah, basically once she said that, I'm like, okay. I was like, good enough to get her hired. She was like, I love Eddie Better. And then. And then like six months later, Eddie Better's touring, like, solo for like the first time ever, and he's playing in Hawaii three shows. And I'm like, you need to work on the Hawaii State tourism board because she was doing sales. So, like, she calls up Hawaii State tourism and she was like, yep, they want to learn about this and take a meeting. I'm like, okay, it's going to be on July 17, 18th, 20. So he, like, flew out there. It was like a little crazy. We were staying in Maui and like, we. It was like some weekend, so we had some time off.
**Rahul Sonnad** *[01:15:59]*: And then we just really had that one meeting. We didn't have anything else. And we took acid and went snorkeling.
**Rahul Sonnad** *[01:16:14]*: Oh, that's amazing.
**Rahul Sonnad** *[01:16:16]*: And that. And in just this beautiful place in Maui, it was like, stunning. And then Autumn like, hit her leg against a piece of coral and just started, like, bleeding out, like, severely. So we like, get her out of the water and I'm like, okay, we gotta go to the hospital. Like, you're horrible. You're, like bleeding. Like, her whole leg is just, like, bleeding and, like blood is gushing out and everything. And, you know, I'm like, trying to stop it with clothing and everything. And she's like, no, I'm too high. I can't go to the hospital. I'm like, no, we gotta go to the hospital. He's like, no, wait, I cannot go in an ambulance to the hospital. And I'm like, I'll drive. And just like, no, we can't go to the hospital. And I'm like, okay.
**Sonia Wendorff** *[01:17:02]*: So we go back to the room and, like, wrap her and everything. It's like, there's still, like, blood oozing out. And we're like, we're next door to the Four Seasons at, like, the Marriott or something, like, kind of in a relatively cheap hotel. And I'm like, okay, I've got an idea. Like, we'll go to the Four Seasons. And they like, that's, you know, kind of like the nicest second is hotel in Hawaii. And I'm like, they've got to have, like, medical people there and everything, because it's, like, super. And. And so I book us two massages, and they're like, yeah, we have a couple massage room open. So I book us that. And I'm like, okay, we'll just go over now and we'll get you, like, treated before the massage.
**Sonia Wendorff** *[01:17:46]*: We'll say, this just happened on the beach and, you know, we need help over there. She's, like, bleeding out, and we do the script and everything. And I'm like, yeah, we just were on the beach here, and, like, she's bleeding and everything. And there's like, yeah, you need to go to the hospital. Then, like, she just wouldn't go to the hospital. So finally they find somebody. I think it was like, the massage people just, like, wrapped her in some, like, first aid kit or something. Yeah, like, it was no medical professional or anything. And then, like, so we're just high as shit during this whole time. And. And then finally, like, they wrap her, we get our massages, and look at that compost down and everything. And then we go to, like, the pool to hang out afterwards. And, like.
**Sonia Wendorff** *[01:18:45]*: And by this time, like, I don't know, such an intense, like, bonding experience. But it was also, like, very early. I forget, like, how early on it was, but I feel like it was, I don't know, three months after she'd started working or something like that. And. And, like, I'm kind of falling in love, and I feel like she's feeling the same way. And I'm like, autumn, what are we gonna do? And, like, I just. That's all I said. She was like, we got a good thing going. We're not gonna fuck it up. And then, like, that was it. Like, after that, were Just like, not like there's no more like romance or. I mean.
**Rahul Sonnad** *[01:19:41]*: I mean, you guys stopped feeling it or.
**Rahul Sonnad** *[01:19:44]*: Yeah, it's still like, it was still like very much in love or anything, but like, it was just like. And again, she had a boyfriend. I was married, like, at the time, so, like, there wasn't really an opportunity and like, it would have been like kind of a company killing problem to have an affair like that. That, like. Yeah. So we just kind of acknowledged. Yeah. Dropped that and just had a great run. Like. Like everything was good after that for. Until she went off to Singapore. But. Yeah, so that's good. We had that experience.
**Rahul Sonnad** *[01:20:23]*: That's mature. Yeah. I mean, so I'm pretty. A pretty good one.
**Rahul Sonnad** *[01:20:28]*: Yeah.
**Rahul Sonnad** *[01:20:30]*: Let's say you're pretty experienced.
**Rahul Sonnad** *[01:20:33]*: And when she wanted to leave and stuff, like, the company started, like, were going really up and we had these amazing times and then kind of things really starting to go down. And she got an offer to be CEO of a company in Singapore. And she's like, I don't know, maybe I should do that. Like, you should definitely do that. Like, because, like, the great thing about being a CEO in Singapore is if it goes well, you'll make a ton of money and you're like, so. Yeah, if it goes badly, like, nobody will know or care like, you Singapore, you've got nothing to lose. Like, you've got only upside. Which maybe didn't turn out to be the case, but.
**Rahul Sonnad** *[01:21:11]*: Yeah. How did she do?
**Sonia Wendorff** *[01:21:16]*: Well, the company did like, okay, but not super well. But that's. I'll tell you the rest of the story later.
**Rahul Sonnad** *[01:21:29]*: Yeah, well, that's. That's all for me. Sorry.
**Sonia Wendorff** *[01:21:37]*: We're done.
**Sonia Wendorff** *[01:21:41]*: Yeah, we're done for today.
**Sonia Wendorff** *[01:21:44]*: John, why is Teacup so lethargic? I don't know. She was sick earlier. Are you feeding her doggy danders? No, arbiturates. But she may be missing Joey. Yeah, that's theory. But while you were here, you hear when her fish was showing up, she got sunlight.`;

const GOALS_RAW = `# Rahul x Sonia - Sponic Gardens goals & vision convo

**Rahul** *[00:02]*: Like across the population, more and more people will start embracing the benefits of AI. Like, I think if you look now, it's kind of weird because from all the people I talk to, this is not the case. But like the surveys of the like US population in general are. People are very anti AI.
**Sonia** *[00:22]*: Yeah.
**Rahul** *[00:26]*: But you know, when you find people who just use like ChatGPT and they get like some really good medical info or something, you know, they kind of switch and they're like, oh, this has really helped me out.
**Sonia** *[00:39]*: Like, yeah, so they switch when they receive direct value in their life. So maybe the onboarding process for people coming in is that we focus on creating some form of value for their personal life. Like we make a website. Like you make a website with this, or you just optimize something about your life and then you're like, oh, actually this is pretty amazing because even people that come here, like, you're very, you promote your setup and AI use because it's absolutely amazing. And most people, even people that are like doers and want to achieve something and already utilize some tools, I see this sense of resistance in them. Like, oh, you know, like yesterday I was talking tom and he's like, oh, I'm just moving something around on my website. And I'm like, you absolutely shouldn't be doing that anymore.
**Sonia** *[01:38]*: And he's like, oh, you know, I'm just doing like cosmetic changes. I'm like, no, like, it's absolutely. You don't do it anymore.
**Rahul** *[01:45]*: On one level, he totally gets it. Yeah, he can see it and he can see everything that was being done. And like, he's, you know, super smart, so he understands it all. But in the other level, it's just like, I don't want to do that. You know, I don't want to use that. It's like, right.
**Sonia** *[01:59]*: Like, where is that coming from? I feel like the amount of time that it takes, like, you need to make this time very sweet for people. And of course everybody should have their internal motivation to be like, I want to prioritize it because it's going to benefit my life. But they don't yet know how it's going to benefit their life. Like, nobody actually understands until taste it. And they're like, oh, I did these things in two hours.
**Rahul** *[02:20]*: I, I think the thing that I wanted to do here but just haven't really motivated on is give everybody like an open claw Hermes agent or something. Yeah, that's like talking to them every day and it's kind of like Helping them. That's their guide.
**Sonia** *[02:37]*: Yeah.
**Rahul** *[02:38]*: And so I think we should get that up and running just with the people here, just as a test.
**Sonia** *[02:43]*: Yeah.
**Rahul** *[02:44]*: You know, and it can be like, encouraging you to take a sauna and explain why or to work out or.
**Sonia** *[02:49]*: Yeah.
**Rahul** *[02:50]*: Tell you about the equipment in the closet.
**Sonia** *[02:52]*: I like that.
**Rahul** *[02:53]*: Yeah, yeah. But. But I think that's like. That's one way you can start adding value. Give people just a general AI agent and, you know, there'll be some talk and cost or whatever, but I think we can just suck that up at the beginning without worrying about it.
**Sonia** *[03:08]*: Yeah.
**Rahul** *[03:08]*: Like a small scale. It doesn't matter.
**Sonia** *[03:10]*: Yeah. Yeah. I also think the evolution of the. The infra page should be like, these are five things that you can do right now that are going to create value for you. One of them being, like, create a website. Just upload all the information about you, clean up your computer, set up your, like, personal project management, like, really easy things. And then you also want to divide.
**Rahul** *[03:35]*: Let's.
**Sonia** *[03:35]*: Let's go to. That's a separate conversation. But I was looking at you showing the page.
**Rahul** *[03:41]*: Yeah. Like, that page.
**Sonia** *[03:46]*: Like, there's too many tools that you want to divide them into. Like, these are the. The ones that you absolutely need. And this is how much time it's going to take. And the next. Yeah. Oh, no, you actually have that. You have it here. You have guys through the setup. Yeah. This is just like.
**Rahul** *[04:03]*: Yeah, it's not well organized and stuff, but it's not.
**Sonia** *[04:06]*: I think it's my goal pretty good.
**Rahul** *[04:07]*: Is not to, like, sell people and get maximum.
**Sonia** *[04:12]*: I know, I know. I know you want it.
**Rahul** *[04:14]*: It's sick.
**Sonia** *[04:15]*: I know. But this is actually relevant because we're talking about, okay, how can we make people more convinced that this is going to benefit their life? So they walk into the space and they're like, oh, this is awesome. Instead of being like, oh, this is kind of weird, you know, But.
**Rahul** *[04:31]*: But I think. I think we want to give people an AI platform for just general use. Because, like, why not? Like, it's not that hard.
**Sonia** *[04:38]*: Yeah.
**Rahul** *[04:38]*: And. And I think we want to make that, like, effortless. Like, not like this. Like,.
**Sonia** *[04:49]*: I mean, like, if you think about how much time that would take you, like five years ago, like, this is effortless.
**Rahul** *[04:56]*: Yeah, totally. Like, this should have taken you, like half a million dollars in a team.
**Sonia** *[05:02]*: Right.
**Rahul** *[05:03]*: Really good people to do things. But. But. But I still think, like, I mean, like, in consumer software, if you have like, six clicks, you lose 80% of people versus you know, one click. So like, yeah, we have to, you know, make it just like Google off. Then you're. It's working, it's talking to you know.
**Sonia** *[05:31]*: Yeah, yeah. So maybe a part of the membership is getting support to having your personal life set up in a way, like getting value as an individual, not only being in the space, but also just like for you to take home. Maybe there's like, I don't know how do you imagine that you setting people up with Hermes? You're talking about this place. Would that be something that you imagine there? Like what kind of setup would you offer people?
**Rahul** *[06:04]*: Just when you join, you just get an agent, you get to name it, you get to interact with it.
**Sonia** *[06:09]*: And then what do they use as an LLM for the agent?
**Rahul** *[06:15]*: Oh well, we'll backend it with something like probably we'll use like a, you know, minimax 2.7 or something like one of the high end open source, like really cheap models.
**Sonia** *[06:27]*: Mm.
**Rahul** *[06:28]*: I mean we can start with Claude or X. Now is really promoting Open Claw.
**Sonia** *[06:36]*: And what do you imagine for Grok? Are there any like enterprise options for.
**Rahul** *[06:45]*: Multi agent? Yeah, yeah, they're all starting to come out. Like also Nvidia has a huge, highly secure like Neoclaw, something like that and they, and Nvidia is giving you free LLM to use it. So yeah, I mean I think for the strategy is like okay, for the first 20 people or something, we don't really care if we have to pay, yeah, $20 a month for them or whatever because it's just like the information from that, like it's better to say with the best LLM it's good enough that it works. And then when we have a cost problem, then we try to optimize cost. But the other way around where you like use a cheap model because you try to optimize cost but it's not good enough. Yeah, people excited.
**Sonia** *[07:45]*: Yeah.
**Rahul** *[07:46]*: That that's like a negative signal because you think like, oh, nobody wants to use this but in fact it's just the model. So if you can use the best model, prove it's good enough and then figure out how to make it cheaper or less or you know, do some things to the expensive, some things to the cheap, you know, but then at least, you know, if you have the good model. So. But I think we, yeah, we definitely set everybody up with a agent. And I don't know if that's Open Claw or Hermits or something.
**Sonia** *[08:20]*: Yes. So people were speaking highly of Hermes and next A couple of days ago, and I'm like, oh, I should just give it. I should give it a go. But I just. I'm just traumatized. I was raped. I was raped by. By Hermes. Chelsea called Oscar yesterday. She, like, was texting me privately too. She, like, oh, we developed a friendship over the weekend. She's just, like, flipping personalities 20 times.
**Rahul** *[08:50]*: I think she's not mentally well.
**Sonia** *[08:52]*: Yeah. I absolutely don't. I. I'm not responding to her at.
**Rahul** *[08:55]*: All with her, like, she's like, really?
**Sonia** *[08:57]*: Yeah, yeah, absolutely. I also told Monique, like, don't even bother anymore. Like, you can spend all day talking to her, and she's just going to get more anxious and more rattled up. Like, just. Just don't. Anyway.
**Rahul** *[09:16]*: Yeah, so. So I think that's another thing. I'd like Hayden to just get up and running, like, because I haven't gotten my head around the agents yet.
**Sonia** *[09:26]*: Yeah. What is Haydn doing with AI?
**Rahul** *[09:35]*: He's been doing a lot of vibe coding he says he's been doing, which actually might be relevant to us doing explainer videos. Like, you take something and then it turns it into a explainer, like, animated video.
**Sonia** *[09:51]*: Oh, cool. Yeah, that's. That's pretty cool. Does he have them on YouTube anywhere?
**Rahul** *[09:57]*: I don't know. I haven't seen him. I'm sure.
**Sonia** *[10:00]*: I mean, I'm sure, but he. It's just like, oh, explain this concept to me. And it creates animation.
**Rahul** *[10:07]*: It's more like you have a web page or something that's yours.
**Sonia** *[10:11]*: Yeah.
**Rahul** *[10:11]*: And then you want to turn that into a video.
**Sonia** *[10:14]*: Yeah.
**Rahul** *[10:15]*: So this is like the conversion process.
**Sonia** *[10:19]*: Well, you. You did that first Pony Gardens, didn't you?
**Rahul** *[10:23]*: Yeah. Though I'd say the quality of that's, like, very low.
**Sonia** *[10:27]*: I like the voice of the.
**Rahul** *[10:29]*: And it didn't. It didn't. Like, it just took the images that were on the site.
**Sonia** *[10:33]*: Yeah.
**Rahul** *[10:33]*: Like, his is building images. Like, it's prompting and building.
**Sonia** *[10:39]*: Mmhmm.
**Rahul** *[10:44]*: All right, I need to eat something.
**Sonia** *[10:46]*: Okay, that sounds like a good idea. Okay, let's see how the voice.`;

import { parseFirefliesMarkdown, parsedTranscriptToMeeting } from "./transcript-parser";

const qaParsed = parseFirefliesMarkdown(QA_RAW);
const goalsParsed = parseFirefliesMarkdown(GOALS_RAW);

const qaMeeting: Meeting = parsedTranscriptToMeeting(qaParsed, {
  id: "meeting-qa",
  title: "Sponic Gardens — Sonia Q&A with Rahul",
  meetingDate: "2026-04-28T05:00:00.000Z",
  summary:
    "Founder Q&A covering equity, governance, demographics, physical infrastructure, and AI infrastructure. Rahul argues for crowd-sourced programming within a strict framework, a 25–45 demographic, low-cost MVP buildout (food/drink, music, A/V; saunas later), and prioritising the CRM-AI as the centerpiece. Sonia challenges around grant funding restrictions, accessibility, and the value to students. They commit to running a small live test of a recorded group dinner with mics in the next two weeks.",
  actionItems: [
    {
      id: "ai-qa-1",
      text: "Run a 5-person dinner with mics in the next two weeks to test voice recognition + AI-generated summary.",
      assigneeLabel: "Rahul Sonnad",
      sourceSegmentId: qaParsed.segments.find((s) => s.text.includes("five person dinner"))?.id ?? null,
      status: "proposed",
    },
    {
      id: "ai-qa-2",
      text: "Buy ~5 lavalier mics (~$40 each) for group recording experiments.",
      assigneeLabel: "Rahul Sonnad",
      sourceSegmentId: qaParsed.segments.find((s) => s.text.includes("40 bucks a piece"))?.id ?? null,
      status: "proposed",
    },
    {
      id: "ai-qa-3",
      text: "Build first version of the CRM-AI: interview every member, vectorise profiles, surface matches.",
      assigneeLabel: "Sonia Wendorff",
      sourceSegmentId: qaParsed.segments.find((s) => s.text.includes("vectorizes"))?.id ?? null,
      status: "proposed",
    },
    {
      id: "ai-qa-4",
      text: "Have Claude scan available Polish/EU grants and shortlist non-restrictive ones.",
      assigneeLabel: null,
      sourceSegmentId: qaParsed.segments.find((s) => s.text.includes("find all the grants"))?.id ?? null,
      status: "proposed",
    },
  ],
});

const goalsMeeting: Meeting = parsedTranscriptToMeeting(goalsParsed, {
  id: "meeting-goals",
  title: "Rahul x Sonia — Sponic Gardens goals & vision",
  meetingDate: "2026-04-29T17:06:00.000Z",
  summary:
    "Strategic conversation on how to onboard members into AI. Rahul wants every joining member to get a personal AI agent (Open Claude / Hermes) as the main 'wow' moment. Sonia pushes for an /infra landing page reframed as 'five things you can do right now' to drive immediate personal value. They agree to start small, eat the LLM cost on the best models, and bring Hayden in to help build the agent setup.",
  actionItems: [
    {
      id: "ai-goals-1",
      text: "Stand up a personal AI agent for every member at join time (start with Open Claude / Hermes).",
      assigneeLabel: "Rahul",
      sourceSegmentId: goalsParsed.segments.find((s) => s.text.includes("just get an agent"))?.id ?? null,
      status: "proposed",
    },
    {
      id: "ai-goals-2",
      text: "Restructure the infra page into 'five things you can do right now' onboarding flow.",
      assigneeLabel: "Sonia",
      sourceSegmentId: goalsParsed.segments.find((s) => s.text.includes("five things"))?.id ?? null,
      status: "proposed",
    },
    {
      id: "ai-goals-3",
      text: "Loop Hayden in on agent setup; ask him about his vibe-coded explainer-video pipeline.",
      assigneeLabel: "Rahul",
      sourceSegmentId: goalsParsed.segments.find((s) => s.text.includes("Hayden"))?.id ?? null,
      status: "proposed",
    },
  ],
});

export const MOCK_MEETINGS: Meeting[] = [goalsMeeting, qaMeeting].sort(
  (a, b) => new Date(b.meetingDate).getTime() - new Date(a.meetingDate).getTime()
);
