-- Open Brain: Semantic AI memory system
-- Reference: https://natesnewsletter.substack.com/p/every-ai-you-use-forgets-you-heres
-- Requires: Supabase with pgvector extension

-- 1. Enable pgvector
CREATE EXTENSION IF NOT EXISTS vector;

-- 2. Create thoughts table (768-dim vectors for Google gemini-embedding-001)
CREATE TABLE IF NOT EXISTS thoughts (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  content TEXT NOT NULL,
  embedding vector(768),
  metadata JSONB,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. HNSW index for fast cosine similarity search (works with any row count)
CREATE INDEX IF NOT EXISTS thoughts_embedding_idx ON thoughts
  USING hnsw (embedding vector_cosine_ops);

CREATE INDEX IF NOT EXISTS thoughts_created_at_idx ON thoughts (created_at DESC);

-- 4. Semantic search function
CREATE OR REPLACE FUNCTION match_thoughts(
  query_embedding vector(768),
  match_threshold float DEFAULT 0.7,
  match_count int DEFAULT 10
) RETURNS TABLE (
  id bigint,
  content text,
  metadata jsonb,
  similarity float
) LANGUAGE plpgsql AS $$
BEGIN
  RETURN QUERY
  SELECT
    t.id,
    t.content,
    t.metadata,
    1 - (t.embedding <=> query_embedding) AS similarity
  FROM thoughts t
  WHERE 1 - (t.embedding <=> query_embedding) > match_threshold
  ORDER BY t.embedding <=> query_embedding
  LIMIT match_count;
END;
$$;

-- 5. Row Level Security — service role only
ALTER TABLE thoughts ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies WHERE tablename = 'thoughts' AND policyname = 'Service role only'
  ) THEN
    CREATE POLICY "Service role only"
      ON thoughts FOR ALL
      USING (auth.role() = 'service_role');
  END IF;
END;
$$;
